query {
  getBookmarkedCourses {
    _id
    title
    description
    content
    author {
      _id
    }
    thumbnail
    slug
    short_link
    views
    tags
    reading_time
    likes {
       _id
    }
    likes {
      _id
    }
    deslikes {
      _id
    }
  }
}
